spring:
    h2:
        console.enabled: true
    liquibase:
        change-log: classpath:/static/db/master.yml
        contexts: dev
    datasource:
        url: jdbc:h2:mem:dev
        driverClassName: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true
springdoc:
    api-docs:
        path: /api/doc
    swagger-ui:
        path: /api/doc-ui